
'use server';

/**
 * @fileOverview A product recommendation AI agent.
 *
 * - getProductRecommendations - A function that handles the product recommendation process.
 * - ProductRecommendationsInput - The input type for the getProductRecommendations function.
 * - ProductRecommendationsOutput - The return type for the getProductRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { UserProfile } from './generate-user-profile';

const ProductRecommendationsInputSchema = z.object({
  userProfile: z.object({
    summary: z.string().describe('A summary of the user profile.'),
    tags: z.array(z.string()).describe('A list of keywords or tags related to the user profile.'),
  }).describe('The user profile generated by the AI.'),
   photoDataUri: z.string().optional().describe("An optional photo of a product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type ProductRecommendationsInput = z.infer<typeof ProductRecommendationsInputSchema>;

const ProductRecommendationsOutputSchema = z.object({
  recommendations: z.array(
    z.object({
      name: z.string().describe('The name of the recommended product or service.'),
      description: z.string().describe('A short description of the recommendation.'),
      imageUrl: z.string().optional().describe('An optional URL to an image of the product or service. This should always be a placeholder from https://placehold.co.'),
      link: z.string().optional().describe('An optional URL to the product or service page.'),
    })
  ).describe('An array of product or service recommendations.'),
});
export type ProductRecommendationsOutput = z.infer<typeof ProductRecommendationsOutputSchema>;

export async function getProductRecommendations(input: ProductRecommendationsInput): Promise<ProductRecommendationsOutput> {
  return productRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'productRecommendationsPrompt',
  input: {schema: ProductRecommendationsInputSchema},
  output: {schema: ProductRecommendationsOutputSchema},
  prompt: `You are a helpful shopping assistant. Based on the following user profile, please provide a list of product or service recommendations.

User Profile Summary: {{{userProfile.summary}}}
User Profile Tags: {{#each userProfile.tags}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
{{#if photoDataUri}}
The user also provided this image for reference: {{media url=photoDataUri}}
{{/if}}

Please provide a list of 3-5 recommendations. For each recommendation, include a name, description, and an optional link. For the imageUrl, you MUST use a placeholder image from 'https://placehold.co/600x400.png'. Do not use any other domain.

Your output should be a JSON object that follows this schema: ${JSON.stringify(ProductRecommendationsOutputSchema.shape)}`,
});

const productRecommendationsFlow = ai.defineFlow(
  {
    name: 'productRecommendationsFlow',
    inputSchema: ProductRecommendationsInputSchema,
    outputSchema: ProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
